/**
 * AI 文档翻译工具
 * 支持多语言文档生成和维护
 * 
 * 使用方法:
 *   node translate-docs.js --input README.md --lang zh,ja,es
 * 
 * 支持语言:
 *   zh: 简体中文
 *   ja: 日本語
 *   es: Español
 *   fr: Français
 *   de: Deutsch
 *   ko: 한국어
 */

const fs = require('fs');
const path = require('path');

// 语言配置
const LANGUAGES = {
  zh: { name: '简体中文', suffix: 'zh-CN' },
  ja: { name: '日本語', suffix: 'ja' },
  es: { name: 'Español', suffix: 'es' },
  fr: { name: 'Français', suffix: 'fr' },
  de: { name: 'Deutsch', suffix: 'de' },
  ko: { name: '한국어', suffix: 'ko' }
};

// 模拟翻译（实际使用应调用翻译 API）
const TRANSLATIONS = {
  zh: {
    'Project Overview': '项目概述',
    'Installation': '安装',
    'Getting Started': '快速开始',
    'API Reference': 'API 参考',
    'Configuration': '配置',
    'Deployment': '部署',
    'Troubleshooting': '故障排除',
    'Contributing': '贡献指南',
    'License': '许可证',
    'Prerequisites': '前置条件',
    'Quick Start': '快速入门',
    'Environment Variables': '环境变量',
    'Examples': '示例',
    'See Also': '参见',
    'More Information': '更多信息',
    'This is a sample project for AI documentation testing.': 
      '这是一个用于 AI 文档测试的示例项目。',
    'The system consists of three main components:': 
      '系统由三个主要组件组成：',
    'For more details, please refer to the documentation.':
      '更多详情请参阅文档。',
    'Make sure you have the following installed:':
      '请确保已安装以下内容：'
  },
  ja: {
    'Project Overview': 'プロジェクト概要',
    'Installation': 'インストール',
    'Getting Started': 'はじめに',
    'API Reference': 'API リファレンス',
    'Configuration': '設定',
    'Deployment': 'デプロイメント',
    'Troubleshooting': 'トラブルシューティング',
    'Contributing': '貢献ガイドライン',
    'License': 'ライセンス',
    'Prerequisites': '前提条件',
    'Quick Start': 'クイックスタート',
    'This is a sample project for AI documentation testing.': 
      'これはAIドキュメントテスト用のサンプルプロジェクトです。'
  },
  es: {
    'Project Overview': 'Descripción del Proyecto',
    'Installation': 'Instalación',
    'Getting Started': 'Primeros Pasos',
    'API Reference': 'Referencia de API',
    'Configuration': 'Configuración',
    'Deployment': 'Despliegue',
    'Troubleshooting': 'Solución de Problemas',
    'Contributing': 'Contribuir',
    'License': 'Licencia',
    'This is a sample project for AI documentation testing.': 
      'Este es un proyecto de ejemplo para pruebas de documentación AI.'
  }
};

/**
 * 模拟 AI 翻译（实际应调用 DeepL/Google/OpenAI API）
 */
function translateContent(content, targetLang) {
  const dict = TRANSLATIONS[targetLang] || {};
  let translated = content;
  
  // 简单替换已知短语
  for (const [en, translatedText] of Object.entries(dict)) {
    const regex = new RegExp(en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    translated = translated.replace(regex, translatedText);
  }
  
  // 添加翻译说明头
  const header = `<!-- 
  Translation: ${LANGUAGES[targetLang]?.name || targetLang}
  Auto-generated by AI Document Translator
  Last updated: ${new Date().toISOString().split('T')[0]}
  Original: ${path.basename(content.split('\n')[0].replace('<!-- Original: ', '').replace(' -->', ''))}
-->

`;
  
  return header + translated;
}

/**
 * 生成语言选择器
 */
function generateLanguageSelector(filename, availableLangs) {
  const baseName = filename.replace('.md', '');
  let selector = '🌐 **Languages**: ';
  
  // 原始语言
  selector += `[English](${filename}) `;
  
  // 其他语言
  for (const lang of availableLangs) {
    const info = LANGUAGES[lang];
    if (info) {
      selector += `| [${info.name}](${baseName}.${info.suffix}.md) `;
    }
  }
  
  return selector + '\n\n---\n\n';
}

/**
 * 同步翻译（保持各语言文档结构一致）
 */
function syncTranslations(sourceFile, targetLangs) {
  const content = fs.readFileSync(sourceFile, 'utf-8');
  const dir = path.dirname(sourceFile);
  const baseName = path.basename(sourceFile, '.md');
  
  const results = [];
  
  for (const lang of targetLangs) {
    const info = LANGUAGES[lang];
    if (!info) continue;
    
    const outputFile = path.join(dir, `${baseName}.${info.suffix}.md`);
    
    // 模拟翻译
    const translated = translateContent(content, lang);
    
    // 写入文件
    fs.writeFileSync(outputFile, translated);
    results.push({ lang, file: outputFile, name: info.name });
  }
  
  return results;
}

/**
 * 生成翻译状态报告
 */
function generateTranslationReport(sourceDir) {
  const files = fs.readdirSync(sourceDir);
  const docs = files.filter(f => f.endsWith('.md') && !f.includes('.'));
  
  const report = {
    timestamp: new Date().toISOString(),
    documents: []
  };
  
  for (const doc of docs) {
    const baseName = doc.replace('.md', '');
    const translations = {};
    
    for (const [lang, info] of Object.entries(LANGUAGES)) {
      const transFile = `${baseName}.${info.suffix}.md`;
      translations[lang] = files.includes(transFile);
    }
    
    report.documents.push({
      source: doc,
      translations
    });
  }
  
  return report;
}

// 主程序
console.log('🌐 AI Document Translator\n');

// 创建示例文档
const sampleDoc = `# Project Documentation

## Project Overview

This is a sample project for AI documentation testing.

## Prerequisites

Make sure you have the following installed:

- Node.js 18+
- npm or yarn

## Installation

\`\`\`bash
npm install
\`\`\`

## Getting Started

### Quick Start

1. Clone the repository
2. Install dependencies
3. Run the development server

## API Reference

For more details, please refer to the documentation.

## Configuration

The system consists of three main components:

- Frontend application
- Backend API
- Database

## Deployment

See deployment guide for details.

## Troubleshooting

Common issues and solutions.

## Contributing

We welcome contributions!

## License

MIT License
`;

// 写入源文档
const sourceFile = './README.md';
fs.writeFileSync(sourceFile, sampleDoc);
console.log(`📄 Source document created: ${sourceFile}`);

// 执行翻译
const targetLangs = ['zh', 'ja', 'es'];
console.log(`\n🔄 Translating to: ${targetLangs.map(l => LANGUAGES[l].name).join(', ')}\n`);

const results = syncTranslations(sourceFile, targetLangs);

results.forEach(r => {
  console.log(`   ✅ ${r.name}: ${path.basename(r.file)}`);
});

// 生成报告
console.log('\n📊 Translation Status:');
const report = generateTranslationReport('.');

report.documents.forEach(doc => {
  console.log(`\n   📄 ${doc.source}`);
  for (const [lang, exists] of Object.entries(doc.translations)) {
    const status = exists ? '✅' : '❌';
    const name = LANGUAGES[lang]?.name || lang;
    console.log(`      ${status} ${name}`);
  }
});

// 创建翻译维护脚本
const maintainScript = `#!/bin/bash
# 翻译维护脚本
# 当源文档更新时，标记翻译为需要更新

echo "🔍 Checking for document updates..."

# 获取源文件的最新修改时间
for file in *.md; do
  if [[ ! "$file" =~ \\.[a-z]{2}(-[A-Z]{2})?\\.md$ ]]; then
    source_mtime=$(stat -f %m "$file")
    base="\${file%.md}"
    
    # 检查各语言版本
    for lang_file in \${base}.*.md; do
      if [ -f "$lang_file" ]; then
        trans_mtime=$(stat -f %m "$lang_file")
        
        if [ $source_mtime -gt $trans_mtime ]; then
          echo "⚠️  $lang_file needs update (source: $file)"
        fi
      fi
    done
  fi
done

echo "✅ Check complete"
`;

fs.writeFileSync('./check-translations.sh', maintainScript);
fs.chmodSync('./check-translations.sh', 0o755);

console.log('\n📝 Generated files:');
console.log('   - README.md (source)');
results.forEach(r => console.log(`   - ${path.basename(r.file)}`));
console.log('   - check-translations.sh (maintenance script)');

console.log('\n💡 Production Tips:');
console.log('   1. Use DeepL API for better translation quality');
console.log('   2. Add human review workflow before publishing');
console.log('   3. Use GitHub Actions to auto-translate on push');
console.log('   4. Implement translation memory for consistency');
